# openapi2-appengine.yaml
swagger: '2.0'
info:
  title: Users API
  description: Sample API on API Gateway with an App Engine backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /hello:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
        address: https://wells-fargo-genai24-8348.ue.r.appspot.com/hello
      responses:
        '200':
          description: A successful response
          schema:
            type: string